In [12]:
import pandas as pd
import numpy as np
import os
datapath_1 = r'F:\\Covid-19 Detection\\chestxray'
dataset_path = r'F:\\Covid-19 Detection\\DataSet2'
categories = os.listdir(dataset_path)
# print(categories)
dataset = pd.read_csv(os.path.join(datapath_1,'metadata.csv'))
findings = dataset['finding']
views = dataset['view']
print(findings[-8:])
print(views)
image_names = dataset['filename']
# print(image_names)

933    Pneumonia/Viral/COVID-19
934    Pneumonia/Viral/COVID-19
935    Pneumonia/Viral/COVID-19
936    Pneumonia/Viral/COVID-19
937    Pneumonia/Viral/COVID-19
938    Pneumonia/Viral/COVID-19
939    Pneumonia/Viral/COVID-19
940    Pneumonia/Viral/COVID-19
Name: finding, dtype: object
0      PA
1      PA
2      PA
3      PA
4      PA
       ..
936    PA
937    AP
938    AP
939    PA
940     L
Name: view, Length: 941, dtype: object


# let's extract all the image index belongs to covid19 and sars

In [16]:
positiveIndex = np.concatenate((np.where(findings[-8:]=='COVID-19')[0],np.where(views=='PA')[0]))
# print(positiveIndex)
positiveImageNames = image_names[positiveIndex]
positiveImageNames

0      auntminnie-a-2020_01_28_23_51_6665_2020_01_28_...
1      auntminnie-b-2020_01_28_23_51_6665_2020_01_28_...
2      auntminnie-c-2020_01_28_23_51_6665_2020_01_28_...
3      auntminnie-d-2020_01_28_23_51_6665_2020_01_28_...
4                                  nejmc2001573_f1a.jpeg
                             ...                        
931                                        16953_3_1.jpg
932                                        16953_4_1.jpg
933                                        16953_5_1.jpg
936            2edb88df42cab5e5fbc18b3965e0bd_jumbo.jpeg
939                                        16865_1_1.jpg
Name: filename, Length: 343, dtype: object

## Extracting the images now

In [17]:
import cv2

for names in positiveImageNames:
    image = cv2.imread(os.path.join(datapath_1,'images',names))
    try:
        cv2.imwrite(os.path.join(dataset_path,categories[1],names),image)
    except Exception as e:
        print(e)

In [6]:
positiveImageNames.shape

(0,)

## Let's extract covid negative images

In [49]:
datapath_2=r'F:\Covid-19 Detection\chest_xray\train\NORMAL'

dataset=pd.read_csv(os.path.join(datapath_2,'Chest_xray_Corona_Metadata.csv'))
findings=dataset['Label']
image_names=dataset['X_ray_image_name']

In [18]:
import random
dataPath_2 = r"F:\Covid-19 Detection\chest_xray\train\NORMAL"
targetDir = "F:\Covid-19 Detection\DataSet2\COVID19 Negatives"

In [62]:
imageNames = os.listdir(dataPath_2)

In [63]:
imageNames

['IM-0115-0001.jpeg',
 'IM-0117-0001.jpeg',
 'IM-0119-0001.jpeg',
 'IM-0122-0001.jpeg',
 'IM-0125-0001.jpeg',
 'IM-0127-0001.jpeg',
 'IM-0128-0001.jpeg',
 'IM-0129-0001.jpeg',
 'IM-0131-0001.jpeg',
 'IM-0133-0001.jpeg',
 'IM-0135-0001.jpeg',
 'IM-0137-0001.jpeg',
 'IM-0140-0001.jpeg',
 'IM-0141-0001.jpeg',
 'IM-0143-0001.jpeg',
 'IM-0145-0001.jpeg',
 'IM-0147-0001.jpeg',
 'IM-0149-0001.jpeg',
 'IM-0151-0001.jpeg',
 'IM-0152-0001.jpeg',
 'IM-0154-0001.jpeg',
 'IM-0156-0001.jpeg',
 'IM-0158-0001.jpeg',
 'IM-0160-0001.jpeg',
 'IM-0162-0001.jpeg',
 'IM-0164-0001.jpeg',
 'IM-0166-0001.jpeg',
 'IM-0168-0001.jpeg',
 'IM-0170-0001.jpeg',
 'IM-0172-0001.jpeg',
 'IM-0176-0001.jpeg',
 'IM-0177-0001.jpeg',
 'IM-0178-0001.jpeg',
 'IM-0180-0001.jpeg',
 'IM-0182-0001.jpeg',
 'IM-0183-0001.jpeg',
 'IM-0185-0001.jpeg',
 'IM-0187-0001.jpeg',
 'IM-0189-0001.jpeg',
 'IM-0191-0001.jpeg',
 'IM-0193-0001.jpeg',
 'IM-0195-0001.jpeg',
 'IM-0199-0001.jpeg',
 'IM-0201-0001.jpeg',
 'IM-0203-0001.jpeg',
 'IM-0205-

In [64]:
type(imageNames)

list

In [65]:
random.shuffle(imageNames)

In [66]:
imageNames

['NORMAL2-IM-1281-0001.jpeg',
 'IM-0623-0001.jpeg',
 'NORMAL2-IM-0810-0001.jpeg',
 'IM-0593-0001.jpeg',
 'IM-0539-0001-0002.jpeg',
 'NORMAL2-IM-1273-0001.jpeg',
 'NORMAL2-IM-0937-0001.jpeg',
 'IM-0250-0001.jpeg',
 'IM-0724-0001.jpeg',
 'NORMAL2-IM-0535-0001.jpeg',
 'NORMAL2-IM-0440-0001.jpeg',
 'IM-0274-0001.jpeg',
 'IM-0439-0001-0002.jpeg',
 'NORMAL2-IM-1241-0001.jpeg',
 'IM-0667-0001.jpeg',
 'NORMAL2-IM-0508-0001.jpeg',
 'IM-0631-0001.jpeg',
 'NORMAL2-IM-1422-0001.jpeg',
 'NORMAL2-IM-0946-0001.jpeg',
 'NORMAL2-IM-0749-0001.jpeg',
 'NORMAL2-IM-1264-0001.jpeg',
 'IM-0191-0001.jpeg',
 'IM-0375-0001.jpeg',
 'NORMAL2-IM-1090-0001.jpeg',
 'NORMAL2-IM-0408-0001.jpeg',
 'NORMAL2-IM-0526-0001.jpeg',
 'NORMAL2-IM-1304-0001.jpeg',
 'NORMAL2-IM-1227-0001.jpeg',
 'IM-0553-0001-0003.jpeg',
 'NORMAL2-IM-0945-0001.jpeg',
 'NORMAL2-IM-0589-0001.jpeg',
 'NORMAL2-IM-1006-0001.jpeg',
 'IM-0748-0001.jpeg',
 'NORMAL2-IM-1209-0001.jpeg',
 'NORMAL2-IM-0772-0001.jpeg',
 'NORMAL2-IM-1198-0001.jpeg',
 'NORMAL2

In [67]:
i = 0
for names in imageNames:
    print(names)
#     imageNames = imageNames[i]
#     print(imageNames)
    image = cv2.imread(os.path.join(dataPath_2,names))
    print(image)
    try:
        cv2.imwrite(os.path.join(targetDir,names),image)
        i+=1
        if i == 343:
            break
    except Exception as e:
        print(e)

NORMAL2-IM-1281-0001.jpeg
[[[ 0  0  0]
  [25 25 25]
  [21 21 21]
  ...
  [ 9  9  9]
  [ 6  6  6]
  [ 4  4  4]]

 [[ 0  0  0]
  [24 24 24]
  [21 21 21]
  ...
  [ 7  7  7]
  [ 5  5  5]
  [ 2  2  2]]

 [[ 0  0  0]
  [23 23 23]
  [20 20 20]
  ...
  [ 7  7  7]
  [ 5  5  5]
  [ 2  2  2]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
IM-0623-0001.jpeg
[[[ 40  40  40]
  [ 42  42  42]
  [ 45  45  45]
  ...
  [224 224 224]
  [234 234 234]
  [243 243 243]]

 [[ 43  43  43]
  [ 44  44  44]
  [ 45  45  45]
  ...
  [234 234 234]
  [241 241 241]
  [249 249 249]]

 [[ 40  40  40]
  [ 41  41  41]
  [ 41  41  41]
  ...
  [235 235 235]
  [240 240 240]
  [249 249 249]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0  

In [50]:
negativeIndex = np.where(findings=='Normal')[0]
negativeImageNames = image_names[negativeIndex]

In [51]:
for names in negativeImageNames:
    image = cv2.imread(os.path.join(datapath_2,'images',names))
    try:
        cv2.imwrite(os.path.join(dataset_path,categories[0],names),image)
    except Exception as e:
        print(e)

(1576,)